#!/bin/bash

[[ -n "${DEBUG}" ]] && exec 3>&1 || exec 3<> /dev/null

log "Installing test-prerequisits ..."
docker-apt shunit2

TEST_SQL="show variables like '%ssl%'; show session status where \`variable_name\` in ('ssl_cipher', 'ssl_verify_mode', 'ssl_version');"

function oneTimeSetUp()
{
	log "Starting supervisord ..."
	/usr/bin/supervisord --configuration=/etc/supervisor/supervisord.conf &
	while [[ ! -f /run/mysqld/mysqld.pid ]] ; do
		log "Waiting for mysqld ..."
		sleep 1
	done

	defaults_root="$(mktemp /tmp/defaults.XXXXXX.cnf)"
	log "Defaults [root] : ${defaults_root}"
	cat <<- EOF > "${defaults_root}"
		[client]
		password="$(cat /run/secrets/mariadb_root_password)"
	EOF
	defaults_user="$(mktemp /tmp/defaults.XXXXXX.cnf)"
	log "Defaults [user] : ${defaults_user}"
	cat <<- EOF > "${defaults_user}"
		[client]
		password="$(cat /run/secrets/mariadb_user_password)"
	EOF
}

function oneTimeTearDown()
{
	rm --force "${defaults_root}" "${defaults_user}"
}

function testCliRootInsecure()
{
	! mysql \
		--defaults-extra-file="${defaults_root}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--user=root 1>&3 2>&3
	assertTrue "CLI as root [insecure]" $?
}

function testCliRootZeroWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_root}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl \
		--user=root 1>&3 2>&3
	assertTrue "CLI as root [zero-way TLS]" $?
}

function testCliRootOneWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_root}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl-ca=/etc/ssl/certs/mariadbca.crt \
		--ssl-verify-server-cert \
		--user=root 1>&3 2>&3
	assertTrue "CLI as root [one-way TLS]" $?
}

function testCliRootTwoWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_root}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl-ca=/etc/ssl/certs/mariadbca.crt \
		--ssl-cert=/etc/ssl/certs/mariadb.crt \
		--ssl-key=/etc/ssl/private/mariadb.key \
		--ssl-verify-server-cert \
		--user=root 1>&3 2>&3
	assertTrue "CLI as root [two-way TLS]" $?
}

function testCliUserInsecure()
{
	! mysql \
		--defaults-extra-file="${defaults_user}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--user="${MARIADB_USER}" 1>&3 2>&3
	assertTrue "CLI as ${MARIADB_USER} [insecure]" $?
}

function testCliUserZeroWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_user}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl \
		--user="${MARIADB_USER}" 1>&3 2>&3
	assertTrue "CLI as ${MARIADB_USER} [zero-way TLS]" $?
}

function testCliUserOneWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_user}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl-ca=/etc/ssl/certs/mariadbca.crt \
		--ssl-verify-server-cert \
		--user="${MARIADB_USER}" 1>&3 2>&3
	assertTrue "CLI as ${MARIADB_USER} [one-way TLS]" $?
}

function testCliUserTwoWayTLS()
{
	mysql \
		--defaults-extra-file="${defaults_user}" \
		--database="${MARIADB_DATABASE}" \
		--execute="${TEST_SQL}" \
		--host=localhost \
		--protocol=tcp \
		--ssl-ca=/etc/ssl/certs/mariadbca.crt \
		--ssl-cert=/etc/ssl/certs/mariadb.crt \
		--ssl-key=/etc/ssl/private/mariadb.key \
		--ssl-verify-server-cert \
		--user="${MARIADB_USER}" 1>&3 2>&3
	assertTrue "CLI as ${MARIADB_USER} [two-way TLS]" $?
}

source /usr/bin/shunit2

